
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://eampjuneqkdhcosidtcs.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhbXBqdW5lcWtkaGNvc2lkdGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTE3OTIsImV4cCI6MjA2MjgyNzc5Mn0.jXFY_wnM3QnaI0uEHUXHKIl3TIjbZJbjzibQmbHi32c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    storageKey: 'supabase.auth.token',
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage
  }
});
